### PR TITLE
remove thebelab option

### PR DESCRIPTION
**Pull request by zelenkastiot**

### CODE REVIEW

**Comment by mathieuboudreau** [comment]
@zelenkastiot is this working correctly? I could have reviewed it =)

**Comment by zelenkastiot** [comment]
Yes, it is. Sorry if I merged it, it was a really tiny fix and I did it after our office hours.
Won't do merges in the future without review.  😕

**Comment by mathieuboudreau** [comment]
Haha no worries, a second set of eyes just never hurt when testing GUIs =)

**Comment by zelenkastiot** [comment]
Hahaha I know. Didn't want to bother you 😄

**Comment by mathieuboudreau** [comment]
Hahaha, you need to stop thinking you're bothering me or @agahkarakuzu. We're here for this, that's why I get paid lol

**Pull request merged**
